### ISSUE TITLE
`Could not load module/asset sizes.` after upgrade from 0.4.0 -> 1.0.0-3

### ISSUE THREAD

**Issue by icd2k3** [FormidableLabs/webpack-dashboard#182]
> Please provide a description of the bug / issue, and provide the details below:
Getting an error after upgrading webpack-dashboard
```
Could not load module/asset sizes.                                                                                                                    
Error: Cannot read property 'length' of undefined                                                                                                      Could not analyze bundle problems.                                                                                                                   undefined
```
====================================================================

###### If the issue is visual, please provide screenshots here
![dashboard](https://www.dropbox.com/s/9az5d3m464qdpt4/Screenshot%202017-08-20%2013.10.26.png?raw=1)
====================================================================

###### Steps to reproduce the problem

Just starting up dashboard causes the issue - code compiles fine, but modules, assets, and problems windows do not render any info
====================================================================

###### Please provide a gist of relevant files

1. My start.sh command:
```
  ./node_modules/.bin/webpack-dashboard -- \
  ./node_modules/.bin/webpack-dev-server \
  --config webpack/webpack.config.js \
  --port 3000 \
  --host [redacted] \
  --history-api-fallback \
  --content-base ./src \
  --open \
  --inline \
  --hot \
  --debug
```
2. webpack.config.js
```
devServer: {
  clientLogLevel: 'none',
  disableHostCheck: true,
  noInfo: true,
  quiet: true,
  stats: 'errors-only',
},
plugins: [
  //...
  new DashboardPlugin(),
]
```

====================================================================

###### More Details

- What operating system are you on? **OSX**
- What terminal application are you using? **iTerm2**
- What version of webpack-dashboard are you using? **1.0.0-3**
- What is the output of running `echo $TERM`? **xterm-256color**
- webpack **v3.5.5**
- webpack-dev-server **v2.7.1**

**Comment by todd-richmond** [comment]
Slightly different error for me with 1.0.0-5. I do have webpack config breaking my code into two modules (app and vendor)

Could not load module/asset sizes.
Error: No code sections found
Could not analyze bundle problems.
Error: No code sections found
  at Bundle.validate (node_modules/inspectpack/lib/models/bundle.js:45:11)

**Comment by ryan-roemer** [comment]
@todd-richmond -- A few questions:

1. Is your bundle minified or otherwise have comments stripped?
2. Do you have `{ output: { pathinfo: true } }` in your webpack configuration?
3. Do you use the new `webpack.optimize.ModuleConcatenationPlugin` plugin?

@kenwheeler @tptee -- If the answer is yes to 1 or 2, then we're going to get `No code sections found` because inspectpack can't read the bundle. Here, you could try/catch for that error, or use the `allowEmpty` inspectpack option to allow code sections to not be found.

If the answer is yes only to 3, then I'm working on that in the playbook for an example, which I'll then add functionality to consume in `inspectpack`.

**Comment by todd-richmond** [comment]
1) not minified or stripped - I only use the dashboard for developer builds. I also have cssmodules and sourcemaps disabled
2) yes - pathinfo: true is set
3) I do not use webpack.optimize.ModuleConcatenationPlugin - had some problem with it when upgrading webpack a while back and so it is currently commented out

**Comment by ryan-roemer** [comment]
Hmm... that _should_ work. Is there some way you can share out your dev bundle (with say real code removed, but webpack structure intact? Or the start of the bundle, with the first few modules included?

**Comment by spock123** [comment]
@ryan-roemer  I have the same issue as @todd-richmond  so I'm not sure it's related to the configuration.

Not using minification, pathinfo is set, not using the ModuleConcatenationPlugin plugin either.
Cheers

**Comment by ryan-roemer** [comment]
@spock123 -- Thanks for the error report. Any chance you can link in a gist of your dev bundle (sanitized for your closed-source code if not an OSS project, maybe by like removing the _actual_ code in every module section but leaving the webpack-built overall structure)?

**Comment by spock123** [comment]
@ryan-roemer I'm not sure I understand - do you mean the webpack configuration? I've split my build into many many files...  or do you actually mean my dev bundle??  I mean, the js bundles?

**Comment by ryan-roemer** [comment]
@spock123 -- Yes, the webpack bundle. You can do a one-off build using the `webpack` cli tool to produce a file-based real bundle. I'm looking for something that looks like this ( https://github.com/FormidableLabs/formidable-playbook/blob/master/examples/frontend/webpack-tree-shaking/dist/js/app1.js ) that I can run `inspectpack` on which is the tool that is involved in the error being thrown.

**Comment by spock123** [comment]
Alright, I'll see what I can do.. it's a project in development, not really OSS but as It's my project I really don't care :)

**Comment by spock123** [comment]
@ryan-roemer  is there a tool to extract just the module structure? I tried to search for one but didn't find it.. tried to manually remove stuff but the bundle has 25000+ lines of code...

**Comment by ryan-roemer** [comment]
@spock123 -- Can you just preserve the top boilerplate + the first say five modules like I demonstrated above and just remove all the rest of the bundle? I can at least see if I can reproduce with that...

**Comment by spock123** [comment]
```
webpackJsonp([6],{

/***/ "./node_modules/@angular-redux/router/lib/esm/actions.js":
/*!***************************************************************!*\
  !*** ./node_modules/@angular-redux/router/lib/esm/actions.js ***!
  \***************************************************************/
/*! exports provided: UPDATE_LOCATION */
/*! exports used: UPDATE_LOCATION */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return UPDATE_LOCATION; });
var UPDATE_LOCATION = "@angular-redux/router::UPDATE_LOCATION";
//# sourceMappingURL=actions.js.map

/***/ }),

/***/ "./node_modules/@angular-redux/router/lib/esm/index.js":
/*!*************************************************************!*\
  !*** ./node_modules/@angular-redux/router/lib/esm/index.js ***!
  \*************************************************************/
/*! exports provided: NgReduxRouterModule, NgReduxRouter, routerReducer, UPDATE_LOCATION */
/*! exports used: routerReducer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
    // REMOVED

/***/ }),

/***/ "./node_modules/@angular-redux/router/lib/esm/reducer.js":
/*!***************************************************************!*\
  !*** ./node_modules/@angular-redux/router/lib/esm/reducer.js ***!
  \***************************************************************/
/*! exports provided: DefaultRouterState, routerReducer */
/*! exports used: routerReducer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
    // REMOVED
/***/ }),

/***/ "./node_modules/@angular-redux/router/lib/esm/router.js":
/*!**************************************************************!*\
  !*** ./node_modules/@angular-redux/router/lib/esm/router.js ***!
  \**************************************************************/
/*! exports provided: NgReduxRouter */
/*! exports used: NgReduxRouter */
/***/ (function(module, __webpack_exports__, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/dev-tools.js":
/*!***************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/dev-tools.js ***!
  \***************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.js":
/*!*************************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/fractal-reducer-map.js ***!
  \*************************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/ng-redux.js":
/*!**************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/ng-redux.js ***!
  \**************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/root-store.js":
/*!****************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/root-store.js ***!
  \****************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/selectors.js":
/*!***************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/selectors.js ***!
  \***************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/components/sub-store.js":
/*!***************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/components/sub-store.js ***!
  \***************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/decorators/dispatch.js":
/*!**************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/decorators/dispatch.js ***!
  \**************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/decorators/helpers.js":
/*!*************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/decorators/helpers.js ***!
  \*************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/decorators/select.js":
/*!************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/decorators/select.js ***!
  \************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/decorators/with-sub-store.js":
/*!********************************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/decorators/with-sub-store.js ***!
  \********************************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/index.js":
/*!************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/index.js ***!
  \************************************************************/
/*! no static exports found */
/*! exports used: NgRedux, NgReduxModule, select */
/***/ (function(module, exports, __webpack_require__) {

/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/***/ }),

/***/ "./node_modules/@angular-redux/store/lib/src/utils/assert.js":
/*!*******************************************************************!*\
  !*** ./node_modules/@angular-redux/store/lib/src/utils/assert.js ***!
  \*******************************************************************/
/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

/*! no static exports found */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {


/*! no static exports found */
/*! all exports used */
```

**Comment by ryan-roemer** [comment]
@spock123 -- Cool. I'll see what I can find with that...

**Comment by ryan-roemer** [comment]
@spock123 -- `inspectpack@1.2.3` may fix this issue (or at least fixes _one_ discovered bug from your bundle sample). Can you manually update your `inspectpack` version in `node_modules` and test out this fix?

@kenwheeler @tptee -- Maybe bump version for `inspectpack@1.2.3` (?)

**Comment by todd-richmond** [comment]
I was using inspectpack@1.3 so that should have been newer than 1.2.3 - correct?

**Comment by ryan-roemer** [comment]
Ugh, we missed the publish changes getting committed.

For now, until we republish, go for `inspectpack@1.2.3` exactly -- this _has_ `1.3.0` changes in it, which we can see with the `publish-diff`

```diff
$ $ publish-diff -o inspectpack@1.3.0 -n inspectpack@1.2.3
Index: HISTORY.md
===================================================================
--- HISTORY.md	inspectpack@1.3.0
+++ HISTORY.md	inspectpack@1.2.3
@@ -1,7 +1,11 @@
 History
 =======
 
+## 1.2.3
+
+* Fix over-truncating `sourceMappingUrl` comment removal.
+
 ## 1.2.2
 
 * Improve module ID comment inference logic.
 * Add `--allow-empty` command flag and internal option for malformed bundles.

Index: lib/parser/extractors.js
===================================================================
--- lib/parser/extractors.js	inspectpack@1.3.0
+++ lib/parser/extractors.js	inspectpack@1.2.3
@@ -104,9 +104,9 @@
 // Matches:
 // //# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uI..."
 const removeSourceMap = function (rawCode) {
   return rawCode && rawCode
-    .replace(/\/\/# sourceMappingURL=[^"]*/g, "") || "";
+    .replace(/\/\/# sourceMappingURL=[^\r\n]*[\r\n]+/g, "") || "";
 };
 
 // Extract the "real" code from Webpack's eval() source map wrapper.
 const getEvalContent = function (node, rawCode) {

Index: lib/utils/compressor.js
===================================================================
--- lib/utils/compressor.js	inspectpack@1.3.0
+++ lib/utils/compressor.js	inspectpack@1.2.3
@@ -113,21 +113,23 @@
         Object.assign({}, sizes, { min }));
     }
 
     return minify(opts)
-      .then(result =>
-        Promise.all([
-          Promise.resolve(result.code.length),
-          getGzipLength(
-            Object.assign({}, opts, {
-              source: result.code
-            })
-          )
-        ]).then(compressedSizes =>
+      .then(result => {
+        if (result.error) {
+          return Promise.reject(result.error);
+        }
+
+        return getGzipLength(
+          Object.assign({}, opts, {
+            source: result.code
+          })
+        ).then(minGz =>
           Object.assign({}, sizes, {
-            min: compressedSizes[0],
-            minGz: compressedSizes[1]
-          })))
+            min: result.code.length,
+            minGz
+          }));
+      })
       .then(fullSizes => {
         if (this._cache) {
           this._cache.set(hashedKey, fullSizes);
           this._cache.save();

Index: package.json
===================================================================
--- package.json	inspectpack@1.3.0
+++ package.json	inspectpack@1.2.3
@@ -1,7 +1,7 @@
 {
   "name": "inspectpack",
-  "version": "1.3.0",
+  "version": "1.2.3",
   "description": "An inspection tool for Webpack frontend JavaScript bundles.",
   "main": "lib/index.js",
   "repository": {
     "type": "git",

Index: test/lib/parser/extractors.spec.js
===================================================================
--- test/lib/parser/extractors.spec.js	inspectpack@1.3.0
+++ test/lib/parser/extractors.spec.js	inspectpack@1.2.3
@@ -1,8 +1,9 @@
 "use strict";
 
 const expect = require("chai").expect;
 const extractors = require("../../../lib/parser/extractors");
+const moduleTypes = require("../../../lib/models/module-types");
 
 describe("lib/parser/extractors", () => {
   describe("#getFileName", () => {
     const getFileName = extractors.getFileName;
@@ -21,5 +22,54 @@
       expect(wrapped("!*** ./foo.js ***!")).to.eql("./foo.js");
       expect(wrapped("!*** ./~/foo.js ***!")).to.eql("./~/foo.js");
     });
   });
+
+  describe("#getCode", () => {
+    const getCode = extractors.getCode;
+    const wrapped = (value) => getCode({
+      start: 0, end: value.length
+    }, moduleTypes.CODE, value);
+
+    it("handles empty code", () => {
+      expect(wrapped("")).to.equal("");
+      expect(wrapped("    ")).to.equal("    ");
+    });
+
+    it("handles basic code", () => {
+      const val = `
+var foo = 'foo';
+var bar = 'bar';
+`;
+      expect(wrapped(val)).to.equal(val);
+    });
+
+    it("removes inline source mapping comments", () => {
+      expect(wrapped(`
+var foo = 'foo';
+//# sourceMappingURL=foo.js.map
+      `).trim()).to.equal("var foo = 'foo';");
+    });
+
+    // Regression Test: https://github.com/FormidableLabs/webpack-dashboard/issues/182
+    it("preserves code after source mapping comments", () => {
+      expect(wrapped(`
+var foo = 'foo';
+//# sourceMappingURL=foo.js.map
+
+var bar = 'bar';
+      `).trim()).to.equal("var foo = 'foo';\nvar bar = 'bar';");
+
+      expect(wrapped(`
+var foo = 'foo';
+//# sourceMappingURL=foo.js.map
+
+var bar = 'bar';
+//# sourceMappingURL=bar.js.map
+
+var baz = 'baz';
+      `).trim()).to.equal("var foo = 'foo';\nvar bar = 'bar';\nvar baz = 'baz';");
+    });
+
+    it("extracts webpack eval source map"); // TODO: Find example.
+  });
 });

Index: test/lib/utils/compressor.spec.js
===================================================================
--- test/lib/utils/compressor.spec.js	inspectpack@1.3.0
+++ test/lib/utils/compressor.spec.js	inspectpack@1.2.3
@@ -1,0 +1,114 @@
\ No newline at end of file
+"use strict";
+
+/**
+ * **Note - Min, GZ**: We're using the current output values for minification
+ * and gzipping, but these are pretty brittle constructs because the libraries
+ * could change under the hood...
+ */
+
+const expect = require("chai").expect;
+const Compressor = require("../../../lib/utils/compressor");
+
+const EMPTY_SIZES = {
+  full: 0,
+  min: "--",
+  minGz: "--"
+};
+const EMPTY_SIZES_GZ = {
+  full: 0,
+  min: 0,
+  minGz: 20 // (Cost of empty gzipping)
+};
+
+describe("lib/utils/compressor", () => {
+  describe("#getFileName", () => {
+    const create = (opts) => new Compressor(opts);
+
+    it("handles empty bundles", () => {
+      const comp = create();
+
+      return Promise.all([
+        comp.getSizes({ source: "" }).then(sizes => {
+          expect(sizes).to.eql(EMPTY_SIZES);
+        }),
+
+        comp.getSizes({ source: "", minified: true, gzip: true }).then(sizes => {
+          expect(sizes).to.eql(EMPTY_SIZES_GZ);
+        }),
+
+        comp.getSizes({ source: "    " }).then(sizes => {
+          expect(sizes).to.eql(Object.assign({}, EMPTY_SIZES, {
+            full: 4
+          }));
+        }),
+
+        comp.getSizes({ source: "    ", minified: true, gzip: true }).then(sizes => {
+          expect(sizes).to.eql(Object.assign({}, EMPTY_SIZES_GZ, {
+            full: 4
+          }));
+        })
+      ]);
+    });
+
+    it("handles basic bundles", () => {
+      const comp = create();
+
+      return Promise.all([
+        comp.getSizes({
+          source: "const foo = () => 'foo';"
+        }).then(sizes => {
+          expect(sizes).to.eql(Object.assign({}, EMPTY_SIZES, {
+            full: 24
+          }));
+        }),
+
+        comp.getSizes({
+          source: "const foo = () => 'foo';",
+          minified: true, gzip: true
+        }).then(sizes => {
+          expect(sizes).to.eql({
+            full: 24,
+            min: 20,
+            minGz: 38
+          });
+        })
+      ]);
+    });
+
+    it("rejects with error on syntax error", () => {
+      return create().getSizes({
+        source: "**SYNTAX_ERROR**",
+        minified: true, gzip: true
+      }).then(sizes => {
+        throw new Error(`Expected failure. Instead got: ${JSON.stringify(sizes)}`);
+      }).catch(err => {
+        expect(err).to.have.property("message", "Unexpected token: operator (**)");
+      });
+    });
+
+    // Regression Test: https://github.com/FormidableLabs/webpack-dashboard/issues/182
+    // (Didn't originally fail, but larger path to process).
+    it("handles source map comments", () => {
+      return create().getSizes({
+        source: `
+a=(function(module, __webpack_exports__, __webpack_require__) {
+
+"use strict";
+/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a",
+function() { return UPDATE_LOCATION; });
+var UPDATE_LOCATION = "@angular-redux/router::UPDATE_LOCATION";
+//# sourceMappingURL=actions.js.map
+
+/***/ })
+`,
+        minified: true, gzip: true
+      }).then(sizes => {
+        expect(sizes).to.eql({
+          full: 310,
+          min: 111,
+          minGz: 124
+        });
+      });
+    });
+  });
+});
```

/cc @tptee

**Comment by ryan-roemer** [comment]
@spock123 -- Okie dokie, `inspectpack@1.3.2` is now latest, greatest, and up-to-datest with all the changes we want. (And a little bit more making it a much smaller package).

**Comment by metju90** [comment]
@ryan-roemer  I've had the same issue and by upgrading to inspectpack@1.3.2 is now working fine.

Thanks for this!

**Comment by spock123** [comment]
@ryan-roemer I can confirm what @metju90 wrote - updating inspectpack to 1.3.2 solves my issues.

Thank you for for great great work!

**Comment by ryansully** [comment]
So should we use `inspectpack@1.2.3` or `inspectpack@1.3.2`?

Also, will dashboard's dependencies be updated and version be bumped to reflect this change? I can submit a PR if that is all that is needed to resolve this issue, unless you have one prepared already.

**Comment by ryan-roemer** [comment]
@ryansully -- `inspectpack@1.3.2` is the correct, most up to date version, and within `webpack-dashboard`'s semver range in `package.json`.

@tptee @kenwheeler -- We _could_ bump `package.json` from `"inspectpack": "^1.3.0",` to `"inspectpack": "^1.3.2",` and we **should** update `yarn.lock` + `package-lock.json` files...

_Side note_ -- we should get a procedure for maybe PRs to ensure **both** `yarn.lock` + `package-lock.json` are regenerated. Currently they have *different* versions of `inspectpack` and the `package-lock.json` file doesn't even meet semver requirements.

**Comment by derkjn** [comment]
Not sure if it's related but I'm getting stuck at the following error:
```
Could not analyze bundle problems.                                                                          ││ idle (1s)                         │
│ Error: Unable to find project root package.json                                                             │└───────────────────────────────────┘
│     at Versions.getData 
```

**Comment by ryan-roemer** [comment]
@derkjn -- It's unrelated. `inspectpack` requires a specified root package.json to run the `versions` action, which you can see here: https://github.com/FormidableLabs/inspectpack/blob/46081b3d294429a3ac9e521621dac078bd995a57/lib/actions/versions.js#L305-L310

I'd open a new issue with your exact setup _and_ file structure including where your `node_modules` lives.

**Comment by FDiskas** [comment]
:fork_and_knife:
![http://i.imgur.com/FgIXjJp.png](http://i.imgur.com/FgIXjJp.png)

**Comment by jpduckwo** [comment]
I'm having an issue after upgrading too. I've tried adding pathinfo: true, my inspectpack is 1.3.2.... any ideas?

Dashboard Log window shows this at the start the repeats with 'could not analyze bundle problems.' 
```
Compiled successfully!                                                                                        
                                                                                                              
   205 modules                                                                                                
/Users/xxxx/node_modules/babylon/lib/index.js:781                                     
    var code = this.input.charCodeAt(this.state.pos);                                                         
                          ^                                                                                   
                                                                                                              
TypeError: this.input.charCodeAt is not a function                                                            
    at Parser.fullCharCodeAtPos (/Users/xxxx/node_modules/babylon/lib/index.js:781:27)
    at Parser.nextToken (/Users/xxxx/node_modules/babylon/lib/index.js:766:34)
    at Parser.parse (/Users/xxxx/node_modules/babylon/lib/index.js:1672:10)                              
    at Object.parse (/Users/xxxx/node_modules/babylon/lib/index.js:7305:37)                              
    at module.exports (/Users/xxxx/node_modules/inspectpack/lib/parser/index.js:103:23)                  
    at new Bundle (/Users/xxxx/node_modules/inspectpack/lib/models/bundle.js:23:16)                      
    at Immediate.validateErr (/Users/xxxx/node_modules/inspectpack/lib/models/bundle.js:266:22)          
    at runCallback (timers.js:666:20)                                                                                            
    at tryOnImmediate (timers.js:639:5)                                                                                          
    at processImmediate [as _immediateCallback] (timers.js:611:5)                                                                
                                                                                                                                 
Could not load module/asset sizes.
```

**Comment by ryan-roemer** [comment]
@jpduckwo / everyone else -- I'm closing this issue since we've solved what originally opened it. Please open new issues with ideally a full reproduction steps (if your project is not open source, please put up a sample repository project with minimum code needed to hit the issue).

Thanks!

**Comment by thecodejack** [comment]
Hi @ryan-roemer  Still getting this error even after having to inspectpack@1.3.2. Any idea what else can be causing the issue?

```
TypeError: this.input.charCodeAt is not a function
    at Parser.fullCharCodeAtPos (/u/user1/.www/application/node_modules/babylon/lib/index.js:781:27)
    at Parser.nextToken (/u/user1/.www/application/node_modules/babylon/lib/index.js:766:34)
    at Parser.parse (/u/user1/.www/application/node_modules/babylon/lib/index.js:1672:10)
    at Object.parse (/u/user1/.www/application/node_modules/babylon/lib/index.js:7305:37)
    at module.exports (/u/user1/.www/application/node_modules/webpack-dashboard/node_modules/inspectpack/lib/parser/index.js:103:23)
    at new Bundle (/u/user1/.www/application/node_modules/webpack-dashboard/node_modules/inspectpack/lib/models/bundle.js:23:16)
    at Immediate.validateErr (/u/user1/.www/application/node_modules/webpack-dashboard/node_modules/inspectpack/lib/models/bundle.js:266:22)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by jpduckwo** [comment]
@thecodejack 
see #193 
Try installing version 1.0.0-7 and additionally the version of inspectpack mentioned in that issue.

**Comment by thecodejack** [comment]
@jpduckwo Thanks. That error is resolved after upgrading to 1.0.0-7. But getting new error. Any leads to solve this?


```
Worker error Error: No code sections found
    at Bundle.validate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Worker error Error: No code sections found
    at Bundle.validate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Worker error Error: No code sections found
    at Bundle.validate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate (/u/user/application/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by mikerogerz** [comment]
Same issue as @thecodejack

**Comment by ryan-roemer** [comment]
@thecodejack @mikerogerz -- If both of you can get me "minimal error reproducing" repositories with latest webpack-dashboard dependency + install / reproduction steps, I'll look into them. Thanks!

**Comment by Jack-Works** [comment]
+1, same issue as @thecodejack. I may try to give a reproduction later

**Comment by Jack-Works** [comment]
Oh, not reproduced it, but found another strange behavior

```sh
yarn global add create-react-app
yarn global add webpack-dashboard
create-react-app temp
cd temp
yarn eject
webpack-dashboard -- ./node_modules/.bin/webpack-dev-server
```
Then nothing happened. (No output for webpack-dashboard)

**Comment by thecodejack** [comment]
@ryan-roemer I will try to create some simple module to reproduce. I was using direct webpack-dev-server since this error, even then getting same error. Looks like issue is with `inspect-webpack` and `webpack 3`.

**Comment by ryan-roemer** [comment]
Make sure to upgrade `inspectpack` to latest version too. It should be fully webpack3 compatible

**Comment by thecodejack** [comment]
yes I have inspeckpack@2.2.1 coming from webpack-dashboard..

**Comment by jpduckwo** [comment]
@thecodejack do you have pathinfo: true in your webpack output?

**Comment by thecodejack** [comment]
nop..but I have added it now and tested..still same error..

**Comment by ryan-codingintrigue** [comment]
@ryan-roemer I've been getting this error too since `1.0.0-7`. I have a pretty big SPA, so it's been hard to get a repro of the issue, but I think I've narrowed it down to something to do with my bundle splitting.

My minimal example outputs a few bundles like this:
```javascript
// bundle.0.js
webpackJsonp([0],[ ...
// bundle.1.js
webpackJsonp([1],{ ...
// etc.
```
However, my large SPA's bundles look like this:
```javascript
// bundle.0.js
webpackJsonp([0],Array(171).concat([
// bundle.1.js
webpackJsonp([1],Array(171).concat([
```

I haven't been able to identify why, but it looks like this is causing the inspectpack [parser/index.js#179](https://github.com/FormidableLabs/inspectpack/blob/master/lib/parser/index.js#L179) to be hit, making the parser assume throw that there "*No code sections found*"

**Comment by ethyde** [comment]
Hi,

I have the same error than @thecodejack, i have push all my config on https://github.com/ethyde/PMD-StarterPack

Install are described in the README : https://github.com/ethyde/PMD-StarterPack#install

If it helps to solve this bug.

**Comment by neutraali** [comment]
We've been getting the same error in a loop since upgrading `webpack` and `webpack-dashboard`, which pretty much renders the dashboard unusable:

```
Worker error Error: No code sections found
	at Bundle.validate (...)
	at createBundle (...)
	at Immediate.setImmediate (...)
	at runCallback (...)
	at tryOnImmediate (...)
	at processImmediate (...)
```
Enabling or disabling `output: { pathinfo }` does not seem to have any effect on the error message. We're using:

```
"webpack": "3.8.1"
"webpack-dashboard": "1.0.2"
"webpack-dev-server": "2.9.4"
```

**Comment by ryan-roemer** [comment]
@neutraali -- We've solved the issue in this original ticket which has to do with the presence of `webpackJsonp([0],Array(171).concat([` in the bundle. If you are having an error, please open a new issue and include a link to a minimal repository that exposes the issues with install + error reproduction steps so that we can more effectively jump in. Thanks!

**Comment by Pushplaybang** [comment]
@thecodejack  - did you solve this or repost your issue?  same here.

**Comment by ryan-roemer** [comment]
@Pushplaybang -- If you've got a reproduction of an error on most current `webpack-dashboard`, please open a new issue ideally with a minimal public repository that has install + error reproduction steps. We can take a look, reproduce the error, and see firsthand what's going on...
