### ISSUE TITLE
Inspectpack is receiving `"[object Object]"` instead of real JavaScript code.

### ISSUE THREAD

**Issue by jpduckwo** [FormidableLabs/webpack-dashboard#193]
### Please provide a description of the bug / issue, and provide the details below:
After upgrade to 1.0.0-5 from 0.4.0 the bundle is not able to be analyzed.

### If the issue is visual, please provide screenshots here
![image](https://user-images.githubusercontent.com/13150911/30674869-54ffa61c-9ec0-11e7-866b-aad73181fe54.png)

### Steps to reproduce the problem
Checkout repo https://github.com/jpduckwo/webpack-dashboard-bug
npm install
npm start
revert webpack-dashboard to 0.4.0 and you'll see it works fine

### Please provide a gist of relevant files
in ./config/webpack/*

### More Details
- What operating system are you on? Mac OS Sierra
- What terminal application are you using? ITerm2
- What version of webpack-dashboard are you using? 1.0.0-5
- What is the output of running `echo $TERM`? xterm-256color

**Comment by servicelevel** [comment]
i am experiencing this same issue also in `1.0.0-7`
is there any solution for this (as i think this or a variation of it had been reported previously)?

**Comment by ryan-roemer** [comment]
I've been working on this today and have been instrumenting code on an improved branch of `inspectpack`. The current traceback of this issue from @jpduckwo 's repository is:

```
 TypeError: this.input.charCodeAt is not a function (source code: [object Object])
    at Parser.fullCharCodeAtPos (/Users/rye/scm/fmd/inspectpack/node_modules/babylon/lib/index.js:781:27)
    at Parser.nextToken (/Users/rye/scm/fmd/inspectpack/node_modules/babylon/lib/index.js:766:34)
    at Parser.parse (/Users/rye/scm/fmd/inspectpack/node_modules/babylon/lib/index.js:1672:10)
    at Object.parse (/Users/rye/scm/fmd/inspectpack/node_modules/babylon/lib/index.js:7305:37)
    at module.exports (/Users/rye/scm/fmd/inspectpack/lib/parser/index.js:189:23)
    at new Bundle (/Users/rye/scm/fmd/inspectpack/lib/models/bundle.js:24:20)
    at Immediate.setImmediate [as _onImmediate] (/Users/rye/scm/fmd/inspectpack/lib/models/bundle.js:277:18)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

The error comes from the fact that the code passed to `inspectpack` / `webpack-dashboard` ends up being `[object Object]` instead of "real JavaScript code` and _that_'s what this babylon parse error is all about.

I'm trying to figure out if it's a problem with the dashboard or the underlying repository.

@servicelevel -- If that stack isn't what you're getting, then please open a new issue with a repository + steps of how to reproduce the error.

**Comment by servicelevel** [comment]
@ryan-roemer nope - same exact issue. thanks for working on this, would be nice to have this working again.

**Comment by ryan-roemer** [comment]
**WACKY**: Here's some instrumented code in inspectpack:

```js
Bundle.create = function (opts, callback) {
  const dummy = new Buffer("I'm a buffer");
  const code = opts.code; // This is **supposed** to be a buffer or string.
  [
    dummy,
    code
  ].forEach((src) => {
    console.log(`\n\n${src}\n`, JSON.stringify({
      isBuffer: Buffer.isBuffer(src),
      keys: Object.keys(opts.code),
      type: src.type,
      length: (src.length || src.data.length).length,
      str: src.toString()
    }, null, 2));
  });
```

Output:

```
I'm a buffer
 {
  "isBuffer": true,
  "keys": [
    "type",
    "data"
  ],
  "str": "I'm a buffer"
}


[object Object]
 {
  "isBuffer": false,
  "keys": [
    "type",
    "data"
  ],
  "type": "Buffer",
  "str": "[object Object]"
}
```

What this means is that somehow `inspectpack` is getting an object that looks like:

```js
{ type: "Buffer", data: [STUFF }
```

That is a plain object and **not** an actual `Buffer`! I'm not sure if something along the webpack-dashboard chain is doing that, or if something upstream is doing that before.

In any case, I might just "not figure it out" and bandaid it by converting the object to a buffer if it's not a string or buffer already...

**Comment by ryan-roemer** [comment]
Fix released in `inspectpack@2.2.1`. This is within `webpack-dashboard@1.0.0-7`'s semver range for `inspectpack` so a reinstall / update should pick up the fixes.

Side note -- for full dev bundle introspection of unminified files, you need to add `output.pathinfo = true` for inspectpack to be able to do it's work.

**Comment by jpduckwo** [comment]
Thanks @ryan-roemer for looking into this! I've tried to install 1.0.0-7 and inspectpack@2.2.1 and now it's just hanging with massive CPU while analyzing the bundle. But it doesn't show any error/stacktrace in the output

I just did this on my test repo ```npm install inspectpack@2.2.1 webpack-dashboard@1.0.0-7 --save-dev``` also tried removingn node_modules and npm install again.

<img width="651" alt="screen shot 2017-10-03 at 11 25 17 am" src="https://user-images.githubusercontent.com/13150911/31105132-80af3c20-a82d-11e7-815a-d5f8384d1f88.png">

**Comment by ryan-roemer** [comment]
@jpduckwo -- Can you let it just run for a little while? When I got your repository running, it took some time to get the first inspectpack run going. Basically, it has to go through all the individual modules in your project, babel parse them, uglify, then gzip -- all computationally intensive.

But after first pass, everything's cached and just incremental changes are recomputed...

**Comment by jpduckwo** [comment]
@ryan-roemer, you're right, leaving it for about 2 minutes worked. But something doesn't seem right for it to take so excruciatingly long for the amount of information you get from it. Version 0.4.0 just popped up pretty much instantly.

I clicked through the file headings and noted that the vendorDLL and polyfills shows a whole bunch of UNKNOWN sections - however that might be because they are generated prior? Could this be slowing it down?

![image](https://user-images.githubusercontent.com/13150911/31109451-b3e0b470-a84b-11e7-8631-b745db01aaad.png)

![image](https://user-images.githubusercontent.com/13150911/31109463-c1d0a7fc-a84b-11e7-8222-fb9afb0351c4.png)

**Comment by ryan-roemer** [comment]
The demo repo looks to have some truly massive files there:

```
$ find dist -name "*.js" -exec du -sh {} \;
412K	dist/dll/polyfills.dll.js
7.4M	dist/dll/vendorDll.dll.js
248K	dist/local/app.js
412K	dist/local/polyfills.dll.js
 32K	dist/local/polyfills.js
4.0K	dist/local/style.js
 36K	dist/local/vendor.js
7.4M	dist/local/vendorDll.dll.js
```

**Comment by ryan-roemer** [comment]
The reason you're getting `UNKNOWN` is that you don't have `output.pathinfo = true` which is needed for `inspectpack` to infer the different submodules of your bundles. This diff enables it in your repo:

```diff
 $ git diff
diff --git a/config/webpack/webpack.dev.js b/config/webpack/webpack.dev.js
index ff8b684..87f2599 100644
--- a/config/webpack/webpack.dev.js
+++ b/config/webpack/webpack.dev.js
@@ -24,6 +24,7 @@ module.exports = webpackMerge(commonConfig, {
 
   output: {
     path: helpers.root('dist', 'local'),
+    pathinfo: true,
     publicPath: 'http://localhost:8080/',
     filename: '[name].js',
     chunkFilename: '[id].chunk.js',
diff --git a/config/webpack/webpack.dll.js b/config/webpack/webpack.dll.js
index 17cb8d0..515e4aa 100644
--- a/config/webpack/webpack.dll.js
+++ b/config/webpack/webpack.dll.js
@@ -14,6 +14,7 @@ module.exports = webpackMerge(coreconfig, {
   output: {
     filename: '[name].dll.js',
     path: helpers.root(constants.DLL_DIST),
+    pathinfo: true,
 
     // The name of the global variable which the library's
     // require() function will be assigned to
diff --git a/config/webpack/webpack.test.js b/config/webpack/webpack.test.js
index 70fc3fd..4851fe5 100644
--- a/config/webpack/webpack.test.js
+++ b/config/webpack/webpack.test.js
@@ -6,5 +6,6 @@ const helpers = require('./helpers');
 module.exports = webpackMerge(prodConfig, {
   output: {
     path: helpers.root('dist', 'test'),
+    pathinfo: true
   },
 });
```

As a side note to why `0.4` was so much faster than the `1.0` candidates is the new version actually looks into the modules parts of a bundle and does all manner of analysis on it. We'll possible make that more tunable (turn-off-able) in the future, but the new dashboard is meant to show deep introspection of information / problems that only come up at the level of each module as opposed to the blunt "whole bundle" approach.

**Comment by jpduckwo** [comment]
Yeah the vendor dll is a concatenation of a bunch of dependencies for the app. This gets optimised and tree shaken when doing a release but not for local dev as the size doesn't matter too much. 

Thanks for all your help!

**Comment by tptee** [comment]
We’re also considering additional pre-cache performance improvements like more granular streaming of results and parallel uglification!

**Comment by ryan-roemer** [comment]
@jpduckwo -- @carlospaelinck is working on some other bugs and figured out that paths of sizes per module weren't being displayed properly when using webpack3. That fix will be landing soon. You _may_ see results sooner after...
